# Generated by Django 6.0.4 on 2026-04-23 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_table', models.CharField(max_length=50)),
                ('seats', models.JSONField(blank=True, default=list, help_text='Pass a JSON array of seat strings')),
                ('price_per_ticket', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tickets', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='movies.movie')),
            ],
        ),
    ]
