# Generated by Django 6.0.4 on 2026-04-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_number', models.IntegerField(unique=True)),
                ('location', models.CharField(max_length=999)),
                ('cinema_image', models.ImageField(blank=True, null=True, upload_to='cinemas/')),
            ],
        ),
    ]
