# Generated by Django 6.0.4 on 2026-04-23 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('title', models.CharField(max_length=999)),
                ('genre', models.CharField(max_length=999)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Total runtime in minutes')),
                ('synopsis', models.TextField()),
                ('casts', models.JSONField(blank=True, default=list, help_text='Pass a JSON array of strings')),
                ('rating', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Now Showing', 'Now Showing'), ('Popular Movies', 'Popular Movies'), ('Coming Soon', 'Coming Soon')], default='Coming Soon', max_length=50)),
                ('cinema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='cinemas.cinema', to_field='cinema_number')),
            ],
        ),
    ]
